name: neomate-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.11,<3.13
  # Core System & Environment
  - psutil>=5.9.0
  - py-cpuinfo>=9.0.0
  - pyyaml>=6.0.3
  - loguru>=0.7.0
  - pydantic>=2.0.0
  # Perception Engine (Hyper-Aware Senses)
  - pyaudio>=0.2.13
  - pvporcupine>=3.0.0
  - faster-whisper>=0.10.0
  - pyannote-audio>=3.0.0
  - webrtcvad>=2.0.10
  - speechbrain>=0.5.16
  - mss>=9.0.1
  - pywin32>=306 # Windows only
  - python-xlib>=0.33 # Linux only
  - easyocr>=1.7.1
  - ultralytics>=8.0.0
  - opencv>=4.8.0
  # Cognitive Core (The Sentient Brain)
  - langchain>=0.1.0
  - aiohttp>=3.9.0
  - llama-cpp-python>=0.2.0
  - duckduckgo-search>=5.0.0
  - beautifulsoup4>=4.12.0
  - requests>=2.31.0
  - chromadb>=0.4.0
  - tinydb>=4.8.0
  - meilisearch>=0.28.0
  # Action & Expression Engine (The Body & Voice)
  - pyautogui>=0.9.54
  - pynput>=1.7.6
  - pycaw>=20230407 # Windows only
  - pyalsaaudio>=0.11.0 # Linux only
  - pyside6>=6.8.0
  - coqui-tts>=0.22.0
  - plyer>=2.1.0
  - rich>=13.7.0
  # AI Foundation
  - pytorch>=2.1.0
  - torchvision>=0.16.0
  - torchaudio>=2.1.0
  # Packaging & Development
  - pyinstaller>=6.0.0
  - pip
  - pip:
      - pytest>=7.4.0
      - black>=23.7.0
      - isort>=5.12.0
      - ruff>=0.0.287
